package com.renthub.auth;
import com.renthub.user.*; import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException; import java.time.LocalDateTime; import java.util.*;
@Service public class AuthService {
 private final UserRepository users; private final AuthSessionRepository sessions; private final PasswordEncoder encoder;
 public AuthService(UserRepository u,AuthSessionRepository s,PasswordEncoder e){users=u;sessions=s;encoder=e;}
 public record UserView(Long id,String fullName,String email,String role,String status){}
 public record AuthResponse(String token,UserView user){}
 private UserView view(User u){return new UserView(u.getId(),u.getFullName(),u.getEmail(),u.getRole(),u.getStatus());}
 @Transactional public AuthResponse register(String name,String email,String password){if(name==null||name.isBlank()||email==null||email.isBlank()||password==null||password.length()<6)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Name, valid email and password of at least 6 characters are required"); if(users.findByEmailIgnoreCase(email.trim()).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Email is already registered"); User u=new User();u.setFullName(name.trim());u.setEmail(email.trim().toLowerCase());u.setPasswordHash(encoder.encode(password));u.setRole("CUSTOMER");u=users.save(u);return issue(u);}
 @Transactional public AuthResponse login(String email,String password){User u=users.findByEmailIgnoreCase(email==null?"":email.trim()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password")); if(!"ACTIVE".equalsIgnoreCase(u.getStatus()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Account is not active"); if("RESET_REQUIRED".equals(u.getPasswordHash())||!encoder.matches(password==null?"":password,u.getPasswordHash()))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Invalid email or password");return issue(u);}
 private AuthResponse issue(User u){AuthSession s=new AuthSession();s.setToken(UUID.randomUUID().toString()+UUID.randomUUID().toString());s.setUserId(u.getId());s.setExpiresAt(LocalDateTime.now().plusDays(7));sessions.save(s);return new AuthResponse(s.getToken(),view(u));}
 public User require(String header){if(header==null||!header.startsWith("Bearer "))throw new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Sign in required");String token=header.substring(7).trim();AuthSession s=sessions.findByToken(token).filter(x->x.getExpiresAt().isAfter(LocalDateTime.now())).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"Session expired. Sign in again"));return users.findById(s.getUserId()).orElseThrow(()->new ResponseStatusException(HttpStatus.UNAUTHORIZED,"User not found"));}
 public UserView me(String header){return view(require(header));}
 @Transactional public void logout(String header){if(header!=null&&header.startsWith("Bearer "))sessions.deleteByToken(header.substring(7).trim());}
 public void requireRole(User u,String... roles){for(String r:roles)if(r.equalsIgnoreCase(u.getRole()))return;throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not have permission for this action");}
}
