CREATE SEQUENCE RH_USER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_CAR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_PROPERTY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_BOOKING_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_SERVICE_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE RH_USERS (
  ID NUMBER PRIMARY KEY, FULL_NAME VARCHAR2(120) NOT NULL, EMAIL VARCHAR2(160) NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR2(200) NOT NULL, ROLE VARCHAR2(30) DEFAULT 'CUSTOMER' NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE RH_CARS (
  ID NUMBER PRIMARY KEY, MAKE VARCHAR2(80) NOT NULL, MODEL VARCHAR2(80) NOT NULL, MODEL_YEAR NUMBER(4) NOT NULL,
  TRANSMISSION VARCHAR2(40) NOT NULL, SEATS NUMBER(2) NOT NULL, DAILY_RATE NUMBER(12,2) NOT NULL,
  CITY VARCHAR2(120) NOT NULL, IMAGE_URL VARCHAR2(500), STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL
);
CREATE TABLE RH_PROPERTIES (
  ID NUMBER PRIMARY KEY, TITLE VARCHAR2(160) NOT NULL, TYPE VARCHAR2(40) NOT NULL, CITY VARCHAR2(120) NOT NULL,
  BEDROOMS NUMBER(2) NOT NULL, BATHROOMS NUMBER(2) NOT NULL, NIGHTLY_RATE NUMBER(12,2) NOT NULL,
  DESCRIPTION VARCHAR2(1000), IMAGE_URL VARCHAR2(500), STATUS VARCHAR2(20) DEFAULT 'AVAILABLE' NOT NULL
);
CREATE TABLE RH_BOOKINGS (
  ID NUMBER PRIMARY KEY, USER_ID NUMBER NOT NULL, ASSET_TYPE VARCHAR2(20) NOT NULL, ASSET_ID NUMBER NOT NULL,
  START_DATE DATE NOT NULL, END_DATE DATE NOT NULL, TOTAL_AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL, CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_BOOKING_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_BOOKING_DATES CHECK (END_DATE > START_DATE),
  CONSTRAINT CK_RH_BOOKING_TYPE CHECK (ASSET_TYPE IN ('CAR','PROPERTY'))
);
CREATE TABLE RH_EXTRA_SERVICES (
  ID NUMBER PRIMARY KEY, NAME VARCHAR2(120) NOT NULL, CATEGORY VARCHAR2(40) NOT NULL, PRICE NUMBER(12,2) NOT NULL,
  DESCRIPTION VARCHAR2(500), IMAGE_URL VARCHAR2(500), STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL
);
CREATE INDEX IX_RH_BOOKINGS_ASSET ON RH_BOOKINGS(ASSET_TYPE, ASSET_ID, START_DATE, END_DATE);
