-- RentHub reconciliation migration.
-- Safe to run repeatedly after a partial/failed 004_complete_platform.sql execution.
-- Oracle / DBeaver compatible when executed as a SQL script.

DECLARE
  n NUMBER;
  PROCEDURE ensure_sequence(p_name VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO n FROM user_sequences WHERE sequence_name = UPPER(p_name);
    IF n = 0 THEN
      EXECUTE IMMEDIATE 'CREATE SEQUENCE ' || p_name || ' START WITH 1 INCREMENT BY 1';
    END IF;
  END;
  PROCEDURE ensure_column(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO n FROM user_tab_columns WHERE table_name = UPPER(p_table) AND column_name = UPPER(p_column);
    IF n = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD ' || p_column || ' ' || p_definition;
    END IF;
  END;
  PROCEDURE ensure_constraint(p_name VARCHAR2, p_sql VARCHAR2) IS
  BEGIN
    SELECT COUNT(*) INTO n FROM user_constraints WHERE constraint_name = UPPER(p_name);
    IF n = 0 THEN
      BEGIN
        EXECUTE IMMEDIATE p_sql;
      EXCEPTION
        WHEN OTHERS THEN
          -- A previous partial migration may already have created the same logical
          -- UNIQUE / FK constraint under an Oracle-generated SYS_* name.
          -- ORA-02261 = such unique or primary key already exists in the table
          -- ORA-02275 = such a referential constraint already exists in the table
          IF SQLCODE NOT IN (-2261, -2275) THEN RAISE; END IF;
      END;
    END IF;
  END;
BEGIN
  ensure_sequence('RH_AUTH_SESSION_SEQ');
  ensure_sequence('RH_FAVORITE_SEQ');
  ensure_sequence('RH_REVIEW_SEQ');
  ensure_sequence('RH_PAYMENT_SEQ');
  ensure_sequence('RH_BOOKING_SERVICE_SEQ');

  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='RH_AUTH_SESSIONS';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RH_AUTH_SESSIONS (ID NUMBER PRIMARY KEY,TOKEN VARCHAR2(100) NOT NULL UNIQUE,USER_ID NUMBER NOT NULL,EXPIRES_AT TIMESTAMP NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;

  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='RH_FAVORITES';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RH_FAVORITES (ID NUMBER PRIMARY KEY,USER_ID NUMBER NOT NULL,ASSET_TYPE VARCHAR2(20) NOT NULL,ASSET_ID NUMBER NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;

  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='RH_REVIEWS';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RH_REVIEWS (ID NUMBER PRIMARY KEY,USER_ID NUMBER NOT NULL,ASSET_TYPE VARCHAR2(20) NOT NULL,ASSET_ID NUMBER NOT NULL,RATING NUMBER(1) NOT NULL,REVIEW_COMMENT VARCHAR2(1000),CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;

  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='RH_PAYMENTS';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RH_PAYMENTS (ID NUMBER PRIMARY KEY,BOOKING_ID NUMBER NOT NULL,USER_ID NUMBER NOT NULL,AMOUNT NUMBER(12,2) NOT NULL,METHOD VARCHAR2(30) NOT NULL,STATUS VARCHAR2(30) DEFAULT ''PAID'' NOT NULL,REFERENCE_NO VARCHAR2(80) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;

  SELECT COUNT(*) INTO n FROM user_tables WHERE table_name='RH_BOOKING_SERVICES';
  IF n=0 THEN EXECUTE IMMEDIATE 'CREATE TABLE RH_BOOKING_SERVICES (ID NUMBER PRIMARY KEY,BOOKING_ID NUMBER NOT NULL,SERVICE_ID NUMBER NOT NULL,PRICE NUMBER(12,2) NOT NULL,CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL)'; END IF;

  ensure_column('RH_CARS','OWNER_ID','NUMBER');
  ensure_column('RH_PROPERTIES','OWNER_ID','NUMBER');

  ensure_constraint('FK_RH_AUTH_USER','ALTER TABLE RH_AUTH_SESSIONS ADD CONSTRAINT FK_RH_AUTH_USER FOREIGN KEY(USER_ID) REFERENCES RH_USERS(ID)');
  ensure_constraint('FK_RH_FAV_USER','ALTER TABLE RH_FAVORITES ADD CONSTRAINT FK_RH_FAV_USER FOREIGN KEY(USER_ID) REFERENCES RH_USERS(ID)');
  ensure_constraint('UQ_RH_FAVORITE','ALTER TABLE RH_FAVORITES ADD CONSTRAINT UQ_RH_FAVORITE UNIQUE(USER_ID,ASSET_TYPE,ASSET_ID)');
  ensure_constraint('FK_RH_REVIEW_USER','ALTER TABLE RH_REVIEWS ADD CONSTRAINT FK_RH_REVIEW_USER FOREIGN KEY(USER_ID) REFERENCES RH_USERS(ID)');
  ensure_constraint('CK_RH_REVIEW_RATING','ALTER TABLE RH_REVIEWS ADD CONSTRAINT CK_RH_REVIEW_RATING CHECK(RATING BETWEEN 1 AND 5)');
  ensure_constraint('UQ_RH_REVIEW','ALTER TABLE RH_REVIEWS ADD CONSTRAINT UQ_RH_REVIEW UNIQUE(USER_ID,ASSET_TYPE,ASSET_ID)');
  ensure_constraint('FK_RH_PAYMENT_BOOKING','ALTER TABLE RH_PAYMENTS ADD CONSTRAINT FK_RH_PAYMENT_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES RH_BOOKINGS(ID)');
  ensure_constraint('FK_RH_PAYMENT_USER','ALTER TABLE RH_PAYMENTS ADD CONSTRAINT FK_RH_PAYMENT_USER FOREIGN KEY(USER_ID) REFERENCES RH_USERS(ID)');
  ensure_constraint('UQ_RH_PAYMENT_BOOKING','ALTER TABLE RH_PAYMENTS ADD CONSTRAINT UQ_RH_PAYMENT_BOOKING UNIQUE(BOOKING_ID)');
  ensure_constraint('UQ_RH_PAYMENT_REF','ALTER TABLE RH_PAYMENTS ADD CONSTRAINT UQ_RH_PAYMENT_REF UNIQUE(REFERENCE_NO)');
  ensure_constraint('FK_RH_BS_BOOKING','ALTER TABLE RH_BOOKING_SERVICES ADD CONSTRAINT FK_RH_BS_BOOKING FOREIGN KEY(BOOKING_ID) REFERENCES RH_BOOKINGS(ID)');
  ensure_constraint('FK_RH_BS_SERVICE','ALTER TABLE RH_BOOKING_SERVICES ADD CONSTRAINT FK_RH_BS_SERVICE FOREIGN KEY(SERVICE_ID) REFERENCES RH_EXTRA_SERVICES(ID)');
  ensure_constraint('UQ_RH_BOOKING_SERVICE','ALTER TABLE RH_BOOKING_SERVICES ADD CONSTRAINT UQ_RH_BOOKING_SERVICE UNIQUE(BOOKING_ID,SERVICE_ID)');
  ensure_constraint('FK_RH_CAR_OWNER','ALTER TABLE RH_CARS ADD CONSTRAINT FK_RH_CAR_OWNER FOREIGN KEY(OWNER_ID) REFERENCES RH_USERS(ID)');
  ensure_constraint('FK_RH_PROPERTY_OWNER','ALTER TABLE RH_PROPERTIES ADD CONSTRAINT FK_RH_PROPERTY_OWNER FOREIGN KEY(OWNER_ID) REFERENCES RH_USERS(ID)');
END;
/

MERGE INTO RH_USERS u USING (SELECT 'RentHub Owner' FULL_NAME,'owner@renthub.local' EMAIL,'RESET_REQUIRED' PASSWORD_HASH,'OWNER' ROLE,'ACTIVE' STATUS FROM dual) s ON (LOWER(u.EMAIL)=LOWER(s.EMAIL)) WHEN NOT MATCHED THEN INSERT (ID,FULL_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS) VALUES (RH_USER_SEQ.NEXTVAL,s.FULL_NAME,s.EMAIL,s.PASSWORD_HASH,s.ROLE,s.STATUS);
MERGE INTO RH_USERS u USING (SELECT 'RentHub Admin' FULL_NAME,'admin@renthub.local' EMAIL,'RESET_REQUIRED' PASSWORD_HASH,'ADMIN' ROLE,'ACTIVE' STATUS FROM dual) s ON (LOWER(u.EMAIL)=LOWER(s.EMAIL)) WHEN NOT MATCHED THEN INSERT (ID,FULL_NAME,EMAIL,PASSWORD_HASH,ROLE,STATUS) VALUES (RH_USER_SEQ.NEXTVAL,s.FULL_NAME,s.EMAIL,s.PASSWORD_HASH,s.ROLE,s.STATUS);

UPDATE RH_CARS SET OWNER_ID=(SELECT ID FROM RH_USERS WHERE LOWER(EMAIL)='owner@renthub.local') WHERE OWNER_ID IS NULL;
UPDATE RH_PROPERTIES SET OWNER_ID=(SELECT ID FROM RH_USERS WHERE LOWER(EMAIL)='owner@renthub.local') WHERE OWNER_ID IS NULL;
COMMIT;

-- Verification summary
SELECT 'RH_AUTH_SESSIONS' OBJECT_NAME, COUNT(*) EXISTS_COUNT FROM user_tables WHERE table_name='RH_AUTH_SESSIONS'
UNION ALL SELECT 'RH_FAVORITES',COUNT(*) FROM user_tables WHERE table_name='RH_FAVORITES'
UNION ALL SELECT 'RH_REVIEWS',COUNT(*) FROM user_tables WHERE table_name='RH_REVIEWS'
UNION ALL SELECT 'RH_PAYMENTS',COUNT(*) FROM user_tables WHERE table_name='RH_PAYMENTS'
UNION ALL SELECT 'RH_BOOKING_SERVICES',COUNT(*) FROM user_tables WHERE table_name='RH_BOOKING_SERVICES';
