-- RentHub business complexity expansion
-- Run once after 005_reconcile_complete_platform.sql

CREATE SEQUENCE RH_COUPON_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_COUPON_USAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_REFUND_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_TICKET_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_NOTIFICATION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_AUDIT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_PAYOUT_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE RH_BOOKINGS ADD COUPON_CODE VARCHAR2(40);
ALTER TABLE RH_BOOKINGS ADD DISCOUNT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL;
ALTER TABLE RH_BOOKINGS ADD CANCELLATION_FEE NUMBER(12,2) DEFAULT 0 NOT NULL;
ALTER TABLE RH_BOOKINGS ADD DEPOSIT_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL;
ALTER TABLE RH_BOOKINGS ADD CHECKIN_STATUS VARCHAR2(30) DEFAULT 'NOT_STARTED' NOT NULL;
ALTER TABLE RH_BOOKINGS ADD OWNER_PAYOUT_STATUS VARCHAR2(30) DEFAULT 'NOT_READY' NOT NULL;

CREATE TABLE RH_COUPONS (
  ID NUMBER PRIMARY KEY,
  CODE VARCHAR2(40) NOT NULL UNIQUE,
  DESCRIPTION VARCHAR2(300),
  DISCOUNT_TYPE VARCHAR2(20) NOT NULL,
  DISCOUNT_VALUE NUMBER(12,2) NOT NULL,
  MIN_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  MAX_DISCOUNT NUMBER(12,2),
  STARTS_AT TIMESTAMP NOT NULL,
  EXPIRES_AT TIMESTAMP NOT NULL,
  GLOBAL_USAGE_LIMIT NUMBER,
  PER_USER_LIMIT NUMBER DEFAULT 1 NOT NULL,
  USED_COUNT NUMBER DEFAULT 0 NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT CK_RH_COUPON_TYPE CHECK (DISCOUNT_TYPE IN ('PERCENT','FIXED')),
  CONSTRAINT CK_RH_COUPON_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED','EXPIRED'))
);

CREATE TABLE RH_COUPON_USAGES (
  ID NUMBER PRIMARY KEY,
  COUPON_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  BOOKING_ID NUMBER NOT NULL UNIQUE,
  DISCOUNT_AMOUNT NUMBER(12,2) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_CU_COUPON FOREIGN KEY (COUPON_ID) REFERENCES RH_COUPONS(ID),
  CONSTRAINT FK_RH_CU_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT FK_RH_CU_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID)
);

CREATE TABLE RH_REFUNDS (
  ID NUMBER PRIMARY KEY,
  BOOKING_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  PAYMENT_ID NUMBER NOT NULL,
  REQUESTED_AMOUNT NUMBER(12,2) NOT NULL,
  APPROVED_AMOUNT NUMBER(12,2),
  FEE_AMOUNT NUMBER(12,2) DEFAULT 0 NOT NULL,
  REASON VARCHAR2(500),
  STATUS VARCHAR2(30) DEFAULT 'REQUESTED' NOT NULL,
  REVIEW_NOTE VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  RESOLVED_AT TIMESTAMP,
  CONSTRAINT FK_RH_REF_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_REF_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT FK_RH_REF_PAYMENT FOREIGN KEY (PAYMENT_ID) REFERENCES RH_PAYMENTS(ID),
  CONSTRAINT CK_RH_REF_STATUS CHECK (STATUS IN ('REQUESTED','APPROVED','REJECTED','PAID'))
);

CREATE TABLE RH_SUPPORT_TICKETS (
  ID NUMBER PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  BOOKING_ID NUMBER,
  CATEGORY VARCHAR2(40) NOT NULL,
  SUBJECT VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(2000) NOT NULL,
  PRIORITY VARCHAR2(20) DEFAULT 'NORMAL' NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
  ASSIGNED_TO NUMBER,
  RESOLUTION VARCHAR2(2000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_TICKET_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT FK_RH_TICKET_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_TICKET_ASSIGNEE FOREIGN KEY (ASSIGNED_TO) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_TICKET_PRIORITY CHECK (PRIORITY IN ('LOW','NORMAL','HIGH','URGENT')),
  CONSTRAINT CK_RH_TICKET_STATUS CHECK (STATUS IN ('OPEN','IN_PROGRESS','WAITING_CUSTOMER','RESOLVED','CLOSED'))
);

CREATE TABLE RH_NOTIFICATIONS (
  ID NUMBER PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  TYPE VARCHAR2(40) NOT NULL,
  TITLE VARCHAR2(200) NOT NULL,
  MESSAGE VARCHAR2(1000) NOT NULL,
  REFERENCE_TYPE VARCHAR2(40),
  REFERENCE_ID NUMBER,
  READ_FLAG NUMBER(1) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_NOTIFICATION_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_NOTIFICATION_READ CHECK (READ_FLAG IN (0,1))
);

CREATE TABLE RH_AUDIT_LOG (
  ID NUMBER PRIMARY KEY,
  ACTOR_USER_ID NUMBER,
  ACTION VARCHAR2(100) NOT NULL,
  ENTITY_TYPE VARCHAR2(60) NOT NULL,
  ENTITY_ID NUMBER,
  OLD_VALUE VARCHAR2(2000),
  NEW_VALUE VARCHAR2(2000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_AUDIT_ACTOR FOREIGN KEY (ACTOR_USER_ID) REFERENCES RH_USERS(ID)
);

CREATE TABLE RH_OWNER_PAYOUTS (
  ID NUMBER PRIMARY KEY,
  OWNER_ID NUMBER NOT NULL,
  BOOKING_ID NUMBER NOT NULL UNIQUE,
  GROSS_AMOUNT NUMBER(12,2) NOT NULL,
  PLATFORM_FEE NUMBER(12,2) NOT NULL,
  PAYOUT_AMOUNT NUMBER(12,2) NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'READY' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  PAID_AT TIMESTAMP,
  CONSTRAINT FK_RH_PAYOUT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT FK_RH_PAYOUT_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT CK_RH_PAYOUT_STATUS CHECK (STATUS IN ('READY','ON_HOLD','PAID'))
);

INSERT INTO RH_COUPONS (ID,CODE,DESCRIPTION,DISCOUNT_TYPE,DISCOUNT_VALUE,MIN_AMOUNT,MAX_DISCOUNT,STARTS_AT,EXPIRES_AT,GLOBAL_USAGE_LIMIT,PER_USER_LIMIT,USED_COUNT,STATUS)
VALUES (RH_COUPON_SEQ.NEXTVAL,'WELCOME10','10% off qualifying bookings','PERCENT',10,100,80,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + NUMTODSINTERVAL(365,'DAY'),500,1,0,'ACTIVE');

INSERT INTO RH_COUPONS (ID,CODE,DESCRIPTION,DISCOUNT_TYPE,DISCOUNT_VALUE,MIN_AMOUNT,MAX_DISCOUNT,STARTS_AT,EXPIRES_AT,GLOBAL_USAGE_LIMIT,PER_USER_LIMIT,USED_COUNT,STATUS)
VALUES (RH_COUPON_SEQ.NEXTVAL,'JORDAN25','25 USD off bookings over 250','FIXED',25,250,NULL,CURRENT_TIMESTAMP,CURRENT_TIMESTAMP + NUMTODSINTERVAL(180,'DAY'),200,2,0,'ACTIVE');

COMMIT;
