-- RentHub enterprise complexity expansion
-- Run once after 006_business_complexity.sql

CREATE SEQUENCE RH_PRICING_RULE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_AVAIL_BLOCK_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_PAYMENT_ATTEMPT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_TICKET_MESSAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_MAINTENANCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_DISPUTE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_BOOKING_HISTORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE RH_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE RH_SYSTEM_CONFIG (
  CONFIG_KEY VARCHAR2(120) PRIMARY KEY,
  CONFIG_VALUE VARCHAR2(1000) NOT NULL,
  VALUE_TYPE VARCHAR2(20) DEFAULT 'STRING' NOT NULL,
  CATEGORY VARCHAR2(60) DEFAULT 'GENERAL' NOT NULL,
  DESCRIPTION VARCHAR2(500),
  UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  UPDATED_BY NUMBER,
  CONSTRAINT FK_RH_CFG_USER FOREIGN KEY (UPDATED_BY) REFERENCES RH_USERS(ID)
);

CREATE TABLE RH_PRICING_RULES (
  ID NUMBER PRIMARY KEY,
  NAME VARCHAR2(160) NOT NULL,
  ASSET_TYPE VARCHAR2(20),
  CITY VARCHAR2(120),
  RULE_TYPE VARCHAR2(30) NOT NULL,
  VALUE NUMBER(12,2) NOT NULL,
  PRIORITY NUMBER DEFAULT 100 NOT NULL,
  START_DATE DATE,
  END_DATE DATE,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  CONSTRAINT CK_RH_PRICE_RULE_TYPE CHECK (RULE_TYPE IN ('PERCENT_UP','PERCENT_DOWN','FIXED_UP','FIXED_DOWN')),
  CONSTRAINT CK_RH_PRICE_RULE_STATUS CHECK (STATUS IN ('ACTIVE','PAUSED'))
);

CREATE TABLE RH_AVAILABILITY_BLOCKS (
  ID NUMBER PRIMARY KEY,
  ASSET_TYPE VARCHAR2(20) NOT NULL,
  ASSET_ID NUMBER NOT NULL,
  START_DATE DATE NOT NULL,
  END_DATE DATE NOT NULL,
  REASON VARCHAR2(500),
  BLOCK_TYPE VARCHAR2(30) DEFAULT 'OWNER_BLOCK' NOT NULL,
  CREATED_BY NUMBER,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT CK_RH_BLOCK_TYPE CHECK (ASSET_TYPE IN ('CAR','PROPERTY')),
  CONSTRAINT FK_RH_BLOCK_USER FOREIGN KEY (CREATED_BY) REFERENCES RH_USERS(ID)
);

CREATE TABLE RH_PAYMENT_ATTEMPTS (
  ID NUMBER PRIMARY KEY,
  BOOKING_ID NUMBER NOT NULL,
  USER_ID NUMBER NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  METHOD VARCHAR2(30) NOT NULL,
  PROVIDER VARCHAR2(50) NOT NULL,
  PROVIDER_REFERENCE VARCHAR2(120),
  STATUS VARCHAR2(30) NOT NULL,
  FAILURE_CODE VARCHAR2(80),
  FAILURE_MESSAGE VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_PA_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_PA_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_PA_STATUS CHECK (STATUS IN ('STARTED','AUTHORIZED','CAPTURED','FAILED'))
);

CREATE TABLE RH_TICKET_MESSAGES (
  ID NUMBER PRIMARY KEY,
  TICKET_ID NUMBER NOT NULL,
  SENDER_USER_ID NUMBER NOT NULL,
  MESSAGE VARCHAR2(2000) NOT NULL,
  INTERNAL_NOTE NUMBER(1) DEFAULT 0 NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_TM_TICKET FOREIGN KEY (TICKET_ID) REFERENCES RH_SUPPORT_TICKETS(ID),
  CONSTRAINT FK_RH_TM_USER FOREIGN KEY (SENDER_USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_TM_INTERNAL CHECK (INTERNAL_NOTE IN (0,1))
);

CREATE TABLE RH_MAINTENANCE (
  ID NUMBER PRIMARY KEY,
  ASSET_TYPE VARCHAR2(20) NOT NULL,
  ASSET_ID NUMBER NOT NULL,
  OWNER_ID NUMBER NOT NULL,
  MAINTENANCE_TYPE VARCHAR2(60) NOT NULL,
  DESCRIPTION VARCHAR2(1000),
  START_DATE DATE NOT NULL,
  END_DATE DATE,
  COST NUMBER(12,2) DEFAULT 0 NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'SCHEDULED' NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_MAINT_OWNER FOREIGN KEY (OWNER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_MAINT_ASSET CHECK (ASSET_TYPE IN ('CAR','PROPERTY')),
  CONSTRAINT CK_RH_MAINT_STATUS CHECK (STATUS IN ('SCHEDULED','IN_PROGRESS','COMPLETED','CANCELLED'))
);

CREATE TABLE RH_DISPUTES (
  ID NUMBER PRIMARY KEY,
  BOOKING_ID NUMBER NOT NULL,
  OPENED_BY NUMBER NOT NULL,
  CATEGORY VARCHAR2(50) NOT NULL,
  DESCRIPTION VARCHAR2(2000) NOT NULL,
  STATUS VARCHAR2(30) DEFAULT 'OPEN' NOT NULL,
  RESOLUTION VARCHAR2(2000),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  RESOLVED_AT TIMESTAMP,
  CONSTRAINT FK_RH_DISP_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_DISP_USER FOREIGN KEY (OPENED_BY) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_DISP_STATUS CHECK (STATUS IN ('OPEN','UNDER_REVIEW','RESOLVED','REJECTED'))
);

CREATE TABLE RH_BOOKING_HISTORY (
  ID NUMBER PRIMARY KEY,
  BOOKING_ID NUMBER NOT NULL,
  OLD_STATUS VARCHAR2(30),
  NEW_STATUS VARCHAR2(30) NOT NULL,
  CHANGED_BY NUMBER,
  REASON VARCHAR2(500),
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_BH_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_BH_USER FOREIGN KEY (CHANGED_BY) REFERENCES RH_USERS(ID)
);

CREATE TABLE RH_USER_DOCUMENTS (
  ID NUMBER PRIMARY KEY,
  USER_ID NUMBER NOT NULL,
  DOCUMENT_TYPE VARCHAR2(50) NOT NULL,
  FILE_NAME VARCHAR2(255) NOT NULL,
  STORAGE_KEY VARCHAR2(500) NOT NULL,
  VERIFICATION_STATUS VARCHAR2(30) DEFAULT 'PENDING' NOT NULL,
  EXPIRY_DATE DATE,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_DOC_USER FOREIGN KEY (USER_ID) REFERENCES RH_USERS(ID),
  CONSTRAINT CK_RH_DOC_STATUS CHECK (VERIFICATION_STATUS IN ('PENDING','VERIFIED','REJECTED','EXPIRED'))
);

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
VALUES('platform.fee.percent','12.5','DECIMAL','FINANCE','Owner platform commission percentage');
INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
VALUES('booking.pending.expiry.hours','24','INTEGER','BOOKING','Pending bookings expire after this many hours');
INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
VALUES('refund.auto.approval.max','150','DECIMAL','FINANCE','Refunds at or below this amount may be auto-approved');
INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
VALUES('support.urgent.sla.hours','2','INTEGER','SUPPORT','Urgent ticket SLA');

INSERT INTO RH_PRICING_RULES(ID,NAME,ASSET_TYPE,CITY,RULE_TYPE,VALUE,PRIORITY,START_DATE,END_DATE,STATUS)
VALUES(RH_PRICING_RULE_SEQ.NEXTVAL,'Amman weekend uplift',NULL,'Amman','PERCENT_UP',12,50,TRUNC(SYSDATE),TRUNC(SYSDATE)+365,'ACTIVE');
INSERT INTO RH_PRICING_RULES(ID,NAME,ASSET_TYPE,CITY,RULE_TYPE,VALUE,PRIORITY,START_DATE,END_DATE,STATUS)
VALUES(RH_PRICING_RULE_SEQ.NEXTVAL,'Property seasonal discount','PROPERTY',NULL,'PERCENT_DOWN',5,80,TRUNC(SYSDATE),TRUNC(SYSDATE)+180,'ACTIVE');

COMMIT;
