-- RentHub business-rule hardening
-- Run once after 008_complex_seed.sql.
-- Makes service compatibility and cancellation policy explicit data, not hidden UI assumptions.

ALTER TABLE RH_EXTRA_SERVICES ADD APPLICABLE_TO VARCHAR2(20) DEFAULT 'BOTH' NOT NULL;
ALTER TABLE RH_EXTRA_SERVICES ADD CONSTRAINT CK_RH_SERVICE_APPL CHECK (APPLICABLE_TO IN ('CAR','PROPERTY','BOTH'));

UPDATE RH_EXTRA_SERVICES SET APPLICABLE_TO='CAR' WHERE NAME IN ('Private Driver','Baby Seat','Roadside Support');
UPDATE RH_EXTRA_SERVICES SET APPLICABLE_TO='PROPERTY' WHERE NAME='Property Cleaning';
UPDATE RH_EXTRA_SERVICES SET APPLICABLE_TO='BOTH' WHERE NAME IN ('Portable Wi-Fi','Airport Transfer');

CREATE SEQUENCE RH_CANCEL_POLICY_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE RH_CANCELLATION_POLICIES (
  ID NUMBER PRIMARY KEY,
  POLICY_CODE VARCHAR2(40) NOT NULL UNIQUE,
  ASSET_TYPE VARCHAR2(20) DEFAULT 'BOTH' NOT NULL,
  MIN_HOURS_BEFORE_START NUMBER NOT NULL,
  FEE_PERCENT NUMBER(5,2) NOT NULL,
  PRIORITY NUMBER DEFAULT 100 NOT NULL,
  STATUS VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  DESCRIPTION VARCHAR2(300),
  CONSTRAINT CK_RH_CANCEL_ASSET CHECK (ASSET_TYPE IN ('CAR','PROPERTY','BOTH')),
  CONSTRAINT CK_RH_CANCEL_STATUS CHECK (STATUS IN ('ACTIVE','INACTIVE')),
  CONSTRAINT CK_RH_CANCEL_FEE CHECK (FEE_PERCENT BETWEEN 0 AND 100)
);

INSERT INTO RH_CANCELLATION_POLICIES(ID,POLICY_CODE,ASSET_TYPE,MIN_HOURS_BEFORE_START,FEE_PERCENT,PRIORITY,STATUS,DESCRIPTION)
VALUES(RH_CANCEL_POLICY_SEQ.NEXTVAL,'FLEX_7D','BOTH',168,0,10,'ACTIVE','Seven or more days before start: full refund');
INSERT INTO RH_CANCELLATION_POLICIES(ID,POLICY_CODE,ASSET_TYPE,MIN_HOURS_BEFORE_START,FEE_PERCENT,PRIORITY,STATUS,DESCRIPTION)
VALUES(RH_CANCEL_POLICY_SEQ.NEXTVAL,'STANDARD_48H','BOTH',48,10,20,'ACTIVE','Two to seven days before start: 10 percent fee');
INSERT INTO RH_CANCELLATION_POLICIES(ID,POLICY_CODE,ASSET_TYPE,MIN_HOURS_BEFORE_START,FEE_PERCENT,PRIORITY,STATUS,DESCRIPTION)
VALUES(RH_CANCEL_POLICY_SEQ.NEXTVAL,'LATE_BEFORE_START','BOTH',1,30,30,'ACTIVE','Less than 48 hours but before start: 30 percent fee');
INSERT INTO RH_CANCELLATION_POLICIES(ID,POLICY_CODE,ASSET_TYPE,MIN_HOURS_BEFORE_START,FEE_PERCENT,PRIORITY,STATUS,DESCRIPTION)
VALUES(RH_CANCEL_POLICY_SEQ.NEXTVAL,'AFTER_START','BOTH',-999999,60,40,'ACTIVE','At or after start: 60 percent fee');

COMMIT;
