-- RentHub cross-domain orchestration hardening
-- Run once after 009_business_rules_hardening.sql

CREATE SEQUENCE RH_PRICE_ADJ_SEQ START WITH 1 INCREMENT BY 1;

ALTER TABLE RH_MAINTENANCE ADD AVAILABILITY_BLOCK_ID NUMBER;
ALTER TABLE RH_MAINTENANCE ADD CONSTRAINT FK_RH_MAINT_BLOCK FOREIGN KEY (AVAILABILITY_BLOCK_ID) REFERENCES RH_AVAILABILITY_BLOCKS(ID);

ALTER TABLE RH_SUPPORT_TICKETS ADD SLA_DUE_AT TIMESTAMP;
ALTER TABLE RH_SUPPORT_TICKETS ADD SLA_STATUS VARCHAR2(20) DEFAULT 'ON_TRACK' NOT NULL;
ALTER TABLE RH_SUPPORT_TICKETS ADD FIRST_RESPONSE_AT TIMESTAMP;
ALTER TABLE RH_SUPPORT_TICKETS ADD CONSTRAINT CK_RH_TICKET_SLA CHECK (SLA_STATUS IN ('ON_TRACK','BREACHED','MET'));

CREATE TABLE RH_BOOKING_PRICE_ADJ (
  ID NUMBER PRIMARY KEY,
  BOOKING_ID NUMBER NOT NULL,
  RULE_ID NUMBER,
  RULE_NAME VARCHAR2(160) NOT NULL,
  RULE_TYPE VARCHAR2(30) NOT NULL,
  AMOUNT NUMBER(12,2) NOT NULL,
  CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  CONSTRAINT FK_RH_BPA_BOOKING FOREIGN KEY (BOOKING_ID) REFERENCES RH_BOOKINGS(ID),
  CONSTRAINT FK_RH_BPA_RULE FOREIGN KEY (RULE_ID) REFERENCES RH_PRICING_RULES(ID)
);

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'support.low.sla.hours','48','INTEGER','SUPPORT','Low-priority support response SLA in hours' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='support.low.sla.hours');

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'support.normal.sla.hours','24','INTEGER','SUPPORT','Normal-priority support response SLA in hours' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='support.normal.sla.hours');

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'support.high.sla.hours','8','INTEGER','SUPPORT','High-priority support response SLA in hours' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='support.high.sla.hours');

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'support.urgent.sla.hours','2','INTEGER','SUPPORT','Urgent support response SLA in hours' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='support.urgent.sla.hours');

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'documents.car.checkin.required','DRIVING_LICENSE','STRING','COMPLIANCE','Verified document required before car check-in' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='documents.car.checkin.required');

INSERT INTO RH_SYSTEM_CONFIG(CONFIG_KEY,CONFIG_VALUE,VALUE_TYPE,CATEGORY,DESCRIPTION)
SELECT 'documents.property.checkin.required','NATIONAL_ID,PASSPORT','STRING','COMPLIANCE','At least one verified identity document required before property check-in' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM RH_SYSTEM_CONFIG WHERE CONFIG_KEY='documents.property.checkin.required');

COMMIT;
